spring:
  application:
    name: hospital

  datasource:
    url: jdbc:h2:tcp://localhost/~/hospital
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      settings:
        web-allow-others: true
